### ISSUE TITLE
can't be build with msvc

### ISSUE THREAD

**Issue by bitbegin** [dcuddeback/libusb-rs#17]
rust msvc environment can't use pkg-config-sys crate. Is there any solutions?

**Comment by Boscop** [comment]
I got it working on windows with a .cargo/config build script override and the dll from here:
https://sourceforge.net/projects/libusb/files/
```toml
[target.x86_64-pc-windows-msvc.'usb-1.0']
rustc-link-search = ['D:\libs\64bit']
rustc-link-lib = ['libusb-1.0']
```
